### ISSUE TITLE
The Mean of Cols and Rows

### ISSUE THREAD

**Issue by yangrui1210** [lalligagger/leo-coverage#1]
Hello, thank you for disclosing this program, which is very helpful to me. However, WHEN I applied it to other satellites, I encountered some problems. I would like to ask what pitch_um, cols and rows represent respectively in Landsat. py. thank you

**Comment by lalligagger** [comment]
Hello, this is a work in progress but the intent is to create your own configuration file that would define sensor properties and satellite information.

The way it is written now, `pitch_um` is the pixel pitch in microns (assumed square), and `rows`/`cols` definite the size of the sensor.

**Comment by dujing1220** [comment]
Hello,Thanks for sharing this project .We found no results when the longitude is less than 0 degrees

**Comment by lalligagger** [comment]
Hi, I'm not sure where you are inputting longitude directly. Also, there might be an AOI masking in the main script. I'd need to see some kind of sample output and, again, I'm actively working on some of the interfaces so I'm not sure it's worth troubleshooting in detail now.

**Comment by dujing1220** [comment]
thanks very much

**Comment by dujing1220** [comment]
> Hi, I'm not sure where you are inputting longitude directly. Also, there might be an AOI masking in the main script. I'd need to see some kind of sample output and, again, I'm actively working on some of the interfaces so I'm not sure it's worth troubleshooting in detail now.

thanks very much
